#ifndef CONFIG_HPP
#define CONFIG_HPP

// UART config
#define UART_ID uart1
#define BAUD_RATE 115200
#define UART_TX 20
#define UART_RX 21

// Automatically cut current off
#define AUTO_DISCONNECT_UPON_CURRENT_LIMIT 0
#define CURRENT_THRESHOLD 6.0

// Relay config
#define RELAY_PIN 26  // A0 -> GPIO26

// Commands
#define GET_VOLTAGE_COMMAND 0x01
#define GET_CURRENT_COMMAND 0x02
#define READ_SENSOR_COMMAND 0x03
#define SET_LED_COMMAND 0x04
#define SET_LEDS_COMMAND 0x05
#define ATTACH_SERVOS_COMMAND 0x06
#define DETACH_SERVOS_COMMAND 0x07
#define SET_SERVO_PULSE_COMMAND 0x08
#define SET_SERVO_PULSES_COMMAND 0x09
#define SET_SERVO_ANGLE_COMMAND 0x0A
#define SET_SERVO_ANGLES_COMMAND 0x0B
#define CONNECT_RELAY_COMMAND 0x0C
#define DISCONNECT_RELAY_COMMAND 0x0D

#endif  // CONFIG_HPP